UPDATE TB_META_FINANCEIRA SET
	META_RECEITA_LIQUIDA = @META_RECEITA_LIQUIDA
	,VALOR_RECEBIMENTO = @VALOR_RECEBIMENTO
	,DATA_ALTERACAO = GETDATE()
	,ID_STATUS = @ID_STATUS
	, META_RECEITA_LIQUIDA_CALC = @META_RECEITA_LIQUIDA_CALC
WHERE
	ID_META_FINANCEIRA = @ID_META_FINANCEIRA