UPDATE TB_META_ANUAL SET
	 ID_UNIDADE_MEDIDA_PAINEL = @ID_UNIDADE_MEDIDA_PAINEL
	,TOTAL = @TOTAL
	,VALOR_MINIMO = @VALOR_MINIMO
	,VALOR_MAXIMO = @VALOR_MAXIMO
	,DATA_ALTERACAO = GETDATE()
	,ID_STATUS = @ID_STATUS
WHERE
	ID_META_ANUAL = @ID_META_ANUAL