	DECLARE @ID_STATUS_APROVACAO UNIQUEIDENTIFIER = (
		SELECT ID_STATUS FROM TB_STATUS_PAINEL WHERE DESCRICAO = @STATUS
	)

UPDATE 
	TB_CABECALHO_PAINEL_META
SET
	ID_STATUS = @ID_STATUS_APROVACAO,
	OBSERVACAO = @OBSERVACAO
WHERE
	ID_META = @ID_META