UPDATE [dbo].[TB_CAPA_PRODUTO]
        SET [CAPA_CORES] = @CAPA_CORES
           ,[CAPA_TIPO_PAPEL] = @CAPA_TIPO_PAPEL
           ,[CAPA_GRAMATURA] = @CAPA_GRAMATURA
           ,[CAPA_ORELHA] = @CAPA_ORELHA
           ,[CAPA_ACABAMENTO] = @CAPA_ACABAMENTO
           ,[CAPA_OBS] = @CAPA_OBS
           ,[CAPA_ACABAMENTO_LOMBADA] = @CAPA_ACABAMENTO_LOMBADA
WHERE [ID_PRODUTO] = @ID_PRODUTO