UPDATE [dbo].[TB_MIOLO_PRODUTO]
SET [MIOLO_PAGINAS] = @MIOLO_PAGINAS
    ,[MIOLO_FORM_ALT] = @MIOLO_FORM_ALT
    ,[MIOLO_FORM_LARG] = @MIOLO_FORM_LARG
    ,[MIOLO_FORM_PESO] = @MIOLO_FORM_PESO
    ,[MIOLO_CORES] = @MIOLO_CORES
    ,[MIOLO_TIPO_PAPEL] = @MIOLO_TIPO_PAPEL
    ,[MIOLO_GRAMATURA] = @MIOLO_GRAMATURA
    ,[MIOLO_OBS] = @MIOLO_OBS
WHERE [ID_PRODUTO] = @ID_PRODUTO