UPDATE [dbo].[TB_CORRESPONDENCIA_AUTOR_BENEFICIARIO]
   SET [AGENDA] = @AGENDA
      ,[ASSUNTO] = @ASSUNTO
      ,[OBS] = @OBS
      ,[CODIGO_INTERNO] = @CODIGO_INTERNO
      ,[ATIVO] = @ATIVO
      ,[ID_AUTOR_BENEFICIARIO] = @ID_AUTOR_BENEFICIARIO
 WHERE ID_CORRESPONDENCIA = @ID_CORRESPONDENCIA