UPDATE [dbo].[PRODUTO]
    SET     [PROD_CDIS] = @PROD_CDIS
           ,[PROD_TEMA] = @PROD_TEMA
           ,[PROD_DISC] = @PROD_DISC
           ,[PROD_MERCADO] = @PROD_MERCADO
           ,[PROD_PROGRAMA] = @PROD_PROGRAMA
           ,[PROD_TIPO] = @PROD_TIPO
           ,[PROD_SELO] = @PROD_SELO
           ,[ID_SELO] = (SELECT ID_SELO FROM TB_SELO_PROTHEUS WHERE DESCRICAO = @PROD_SELO)
           ,[PROD_SEGM] = @PROD_SEGM
           ,[PROD_AEDU] = @PROD_AEDU
           ,[PROD_COMP] = @PROD_COMP
           ,[PROD_FAIXAETARIA] = @PROD_FAIXAETARIA
           ,[PROD_ASSU] = NULL
           ,[PROD_GTEX] = @PROD_GTEX
           ,[PROD_PREMIACAO] = @PROD_PREMIACAO
           ,[PROD_VERSAO] = @PROD_VERSAO
           ,[PROD_COLE] = @PROD_COLE
           ,[PROD_TITULO] = @PROD_TITULO
           ,[PROD_EDICAO] = @PROD_EDICAO
           ,[PROD_MIDI] = @PROD_MIDI
           ,[PROD_PAGINAS] = NULL
           ,[PROD_PLAT] = @PROD_PLAT
           ,[PROD_FORALTURA] = NULL
           ,[PROD_FORLARGURA] = NULL
           ,[PROD_PESO] = NULL
           ,[PROD_PUBLICACAO] = @PROD_PUBLICACAO
           ,[PROD_ISBN] = @PROD_ISBN
           ,[PROD_STATUS] = @PROD_STATUS
           ,[PROD_CODBARRAS] = @PROD_CODBARRAS
           ,[PROD_SINOPSE] = @PROD_SINOPSE
           ,[PROD_PRECO] = NULL
           ,[PROD_EBSA] = @PROD_EBSA
           ,[PROD_UNIDADE] = NULL
           ,[PROD_CODPROT] = NULL
           ,[PROD_PUBLICADO] = NULL
           ,[PROD_ORIGEM] = @PROD_ORIGEM
           ,[EXCLUIDO] = 0
           ,[PROD_TIPO_PRODUTO] = @PROD_TIPO_PRODUTO
           ,[PROD_UNIDADE_MEDIDA] = @PROD_UNIDADE_MEDIDA
           ,[ID_GRUPO] = NULL
           ,[ID_SEGMENTO] = @ID_SEGMENTO
           ,[PROD_VIDEO] = NULL
           ,[PROD_NOME_CAPA] = @PROD_NOME_CAPA
           ,[ANO_PROGRAMA] = @ANO_PROGRAMA
           ,[PROD_INTEGRADO] = 'naoIntegrado'
WHERE [PROD_ID] = @PROD_ID