SELECT 
	TRA.CODIGO_PROTHEUS AS REGIAO
FROM 
	TB_REGIAO_ATUACAO TRA
INNER JOIN
	TB_USUARIO_RM TU
	ON TRA.ID_REGIAO_ATUACAO = TU.ID_REGIAO_ATUACAO
WHERE
	TU.ID_USUARIO_RM = @ID_USUARIO
AND
	TU.ATIVO = 1