SELECT 
	COUNT(*) + 1 AS DIGITO_SEQUENCIAL
FROM 
	PRODUTO
WHERE
	PROD_MERCADO = @PROD_MERCADO
AND
	PROD_AEDU = @PROD_AEDU
AND
	PROD_DISC = @PROD_DISC
AND
	PROD_MIDI = @PROD_MIDI
AND
	PROD_TIPO = @PROD_TIPO
AND
	PROD_EDICAO = @PROD_EDICAO
AND
	PROD_VERSAO	= @PROD_VERSAO