SELECT
	 LIN.ID_META
	,LIN.ID_LINHA_META
	,LIN.INDICADOR
    ,LIN.META
    ,LIN.PESO
	,ORI.ID_ORIGEM
	,ORI.DESCRICAO
FROM 
	TB_LINHA_PAINEL_META AS LIN
INNER JOIN
	TB_ORIGEM_DADOS_PAINEL_META AS ORI
	ON LIN.ID_ORIGEM = ORI.ID_ORIGEM
WHERE
	((@ID_LINHA_META IS NULL) OR (LIN.ID_LINHA_META = @ID_LINHA_META))
AND
	((@ID_META IS NULL) OR (LIN.ID_META = @ID_META))


