SELECT 
	U.NOME,
	U.DATA_INICIO AS DATA_ADMISSAO,
	U.DATA_FIM AS DATA_DEMISSAO,
	C.DESCRICAO AS CARGO,
	CONCAT(F.NOME_FANTASIA, ' - ', F.UF) AS FILIAL,
	PM.DATA_INICIO AS DATA_INICIO_CAMPANHA,
	PM.DATA_FIM AS DATA_FIM_CAMPANHA
FROM 
	TB_USUARIO_RM AS U
INNER JOIN
	TB_CARGO AS C
	ON U.ID_CARGO = C.ID_CARGO
INNER JOIN
	TB_FILIAL AS F
	ON U.ID_FILIAL = F.ID_FILIAL
INNER JOIN
	TB_PERIODO_META AS PM
	ON GETDATE() BETWEEN PM.DATA_INICIO AND PM.DATA_FIM
WHERE
	U.ID_USUARIO_RM = @ID_USUARIO
AND
	U.ATIVO = 1
