SELECT
	SC.ID_CONSULTOR AS ID_USUARIO_RM,
	(SELECT NOME FROM TB_USUARIO_RM WHERE ID_USUARIO_RM = SC.ID_CONSULTOR) AS NOME,
	'' AS ID_CARGO,
	'' AS ID_FILIAL,
	'' AS ID_REGIAO_ATUACAO,
	'' AS DATA_INICIO,
	'' AS DATA_FIM,
	'' AS ID_SECAO,
	'' AS CODIGO_FILIAL,
	'' AS NUMERO_CHAPA
FROM 
	TB_USUARIO_RM AS U
LEFT JOIN
	TB_GERENTE_SUPERVISOR AS GS
	ON U.ID_USUARIO_RM = GS.ID_GERENTE
LEFT JOIN
	TB_SUPERVISOR_CONSULTOR AS SC
	ON (GS.ID_SUPERVISOR = SC.ID_SUPERVISOR OR U.ID_USUARIO_RM = SC.ID_SUPERVISOR)
INNER JOIN
	TB_REGIAO_ATUACAO R
	ON U.ID_REGIAO_ATUACAO = R.ID_REGIAO_ATUACAO
WHERE
	U.ID_USUARIO_RM = @ID_USUARIO_RM
AND
	((@ID_REGIAO = '00000000-0000-0000-0000-000000000000') OR (R.ID_REGIAO_ATUACAO = @ID_REGIAO))
AND
	SC.ID_CONSULTOR IS NOT NULL
AND
	U.ATIVO = 1
AND
	U.CODIGO_PROTHEUS IS NOT NULL