SELECT
	 CAB.ID_META
    ,CAB.ID_GRUPO_PAINEL
	,TGP.DESCRICAO as DESCRICAO_GRUPO
    ,CAB.ID_STATUS
	,TSP.DESCRICAO as DESCRICAO_STATUS
    ,CAB.OBSERVACAO
FROM 
	TB_CABECALHO_PAINEL_META AS CAB
INNER JOIN
	TB_STATUS_PAINEL AS TSP
	ON TSP.ID_STATUS = CAB.ID_STATUS
INNER JOIN
	TB_GRUPO_PAINEL AS TGP
	ON TGP.ID_GRUPO_PAINEL = CAB.ID_GRUPO_PAINEL
INNER JOIN
	TB_LINHA_PAINEL_META AS LIN
	ON CAB.ID_META = LIN.ID_META
INNER JOIN
	TB_ORIGEM_DADOS_PAINEL_META AS ORI
	ON LIN.ID_ORIGEM = ORI.ID_ORIGEM
INNER JOIN
	TB_PERIODO_META AS PER
	ON ORI.ID_PERIODO = PER.ID_PERIODO
WHERE
	((@ID_META IS NULL OR @ID_META = '00000000-0000-0000-0000-000000000000') OR (CAB.ID_META = @ID_META))
AND
	((@ID_GRUPO_PAINEL IS NULL OR @ID_GRUPO_PAINEL = '00000000-0000-0000-0000-000000000000') OR (CAB.ID_GRUPO_PAINEL = @ID_GRUPO_PAINEL))
AND
	((@ID_STATUS_PAINEL IS NULL OR @ID_STATUS_PAINEL = '00000000-0000-0000-0000-000000000000') OR (CAB.ID_STATUS = @ID_STATUS_PAINEL))
AND
	((@OBSERVACAO IS NULL) OR (@OBSERVACAO = '') OR (CAB.OBSERVACAO LIKE '%'+@OBSERVACAO+'%'))
AND
	((@ID_PERIODO IS NULL OR @ID_PERIODO = '00000000-0000-0000-0000-000000000000') OR (PER.ID_PERIODO = @ID_PERIODO))
GROUP BY CAB.ID_META
    ,CAB.ID_GRUPO_PAINEL
	,TGP.DESCRICAO
    ,CAB.ID_STATUS
	,TSP.DESCRICAO
    ,CAB.OBSERVACAO