SELECT 
	 ACESSO_MODIFICACAO
	,ACESSO_VISUALIZACAO
	,NOME_ABA
FROM 
	TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO AS REGRA
INNER JOIN
	TB_ABA_CADASTRO_PRODUTO AS ABA
	ON ABA.ID_ABA = REGRA.ID_ABA
WHERE
	ID_USUARIO = @ID_USUARIO