SELECT
	 R.[ID_REGIAO_ATUACAO] AS ID_REGIAO 
    ,R.[DESCRICAO]
    ,R.CODIGO_PROTHEUS AS UF
    ,GETDATE() AS DT_CADASTRO
FROM 
	TB_USUARIO_RM AS U
INNER JOIN
	TB_REGIAO_ATUACAO R
	ON U.ID_REGIAO_ATUACAO = R.ID_REGIAO_ATUACAO
WHERE
	U.ID_USUARIO_RM = @ID_USUARIO_RM
AND
	U.ATIVO = 1
    