SELECT p.PROD_ID
	, p.PROD_TITULO
	, p.PROD_EBSA
	, p.PROD_ISBN
	, p.PROD_PUBLICADO
	, p.PROD_INTEGRADO
	, A.AEDU_DESCRICAO
	, p.PROD_VIDEO
	, p.PROD_PRECO
	, (SELECT COUNT(*) FROM PRODUTO WHERE EXCLUIDO = 0) AS CONTAGEM
FROM PRODUTO p
LEFT JOIN ANO_EDUCACAO AS A 
	ON p.PROD_AEDU = A.AEDU_ID
WHERE EXCLUIDO = 0
ORDER BY p.PROD_TITULO
OFFSET ((@NumeroPagina) * @RegistrosPagina) ROWS
FETCH NEXT @RegistrosPagina ROWS ONLY;