SELECT T.[ID_LOG_AUTOR]
      ,T.[ID_AUTOR]
      ,T.[DATA_LOG]
      ,T.[DESCRICAO_LOG]
      ,T.[ID_USUARIO]
	  ,U.NOME
  FROM [dbo].[TB_LOG_AUTOR_BENEFICIARIO] T
JOIN USUARIO U ON U.ID_USUARIO = T.ID_USUARIO
WHERE ID_AUTOR = @ID_AUTOR;