SELECT PT.PTEM_ID
      ,PT.PTEM_TEMA
      ,PT.PTEM_PROD
      ,T.TEMA_DESCRICAO
      ,T.TEMA_TIPO
  FROM [dbo].[PRODUTO_TEMATRANS] PT
JOIN TEMA T ON PT.PTEM_TEMA = T.TEMA_ID
  WHERE [PTEM_PROD] = @IdProduto