SELECT PD.PDES_ID
      ,PD.PDES_DAES
      ,PD.PDES_PROD
	  ,DE.DAES_DESCRICAO
	  ,de.DAES_DIA
  FROM [dbo].[PRODUTO_DATAESPECIAL] PD
JOIN DATA_ESPECIAL DE ON PD.PDES_DAES = DE.DAES_ID
  WHERE [PDES_PROD] = @IdProduto