SELECT DISTINCT 
	 C.[ID_CARGO]
	,C.[DESCRICAO]
	,C.[ID_HIERARQUIA]
	,C.[ID_GRUPO_PAINEL]
	,C.[DT_CADASTRO]
	,C.[ATIVO]
FROM 
	TB_CARGO AS C 
INNER JOIN 
	TB_USUARIO_RM AS U
	ON C.ID_CARGO = U.ID_CARGO 
WHERE
	U.ID_USUARIO_RM IN 
	(
		SELECT
			ISNULL(SC.ID_CONSULTOR, GS.ID_SUPERVISOR) AS ID_USUARIO
		FROM 
			TB_USUARIO_RM AS U
		LEFT JOIN
			TB_GERENTE_SUPERVISOR AS GS
			ON U.ID_USUARIO_RM = GS.ID_GERENTE
		LEFT JOIN
			TB_SUPERVISOR_CONSULTOR AS SC
			ON (GS.ID_SUPERVISOR = SC.ID_SUPERVISOR OR U.ID_USUARIO_RM = SC.ID_SUPERVISOR)
		WHERE
			U.ID_USUARIO_RM  = 
			(
				SELECT DISTINCT RM.ID_USUARIO_RM
				FROM 
					__PROTHEUS__.dbo.SA2010 AS FORNECEDOR
				INNER JOIN
					EBSA.dbo.TB_USUARIO_RM AS RM
					ON FORNECEDOR.A2_CGC = RM.CPF COLLATE Latin1_General_CI_AS
				INNER JOIN
					EBSA.dbo.USUARIO AS USR
					ON FORNECEDOR.A2_EMAIL = USR.EMAIL COLLATE Latin1_General_CI_AS	
				WHERE 
					LEN(A2_EMAIL) > 0
				AND
					USR.ID_USUARIO = @ID_USUARIO
			)
	)
AND
	U.[ATIVO] = 1