SELECT
	 [pma].[ID_META_ANUAL]
	,[urm].[ID_USUARIO_RM]
	,[lpm].[ID_LINHA_META]
	,[pma].[ID_UNIDADE_MEDIDA_PAINEL]
	,[urm].[NOME]
	,[car].[ID_CARGO]
	,[car].[DESCRICAO] AS CARGO
	,[gru].[DESCRICAO] AS GRUPO_PAINEL
	,[lpm].[META]
	,[lpm].[ID_META]
	,[lpm].[INDICADOR]
	,[lpm].[PESO]
	,[pma].[UNIDADE_MEDIDA]
	,[pma].[META_ANUAL]
	,[pma].[VALOR_MINIMO]
	,[pma].[VALOR_MAXIMO]
	,[pma].[ID_STATUS]
	,[pma].[SITUACAO]
	,[cpm].[OBSERVACAO]
	,[pma].[DATA_CRIACAO]
	,[pma].[DATA_ALTERACAO]
	,[r].[CODIGO_PROTHEUS] AS REGIAO
	,[urm].[DATA_INICIO] AS ADMISSAO
	,[urm].[DATA_FIM] AS DEMISSAO
	,[r].[CODIGO_PROTHEUS] AS UF
FROM
	[TB_USUARIO_RM] [urm]
INNER JOIN
	TB_REGIAO_ATUACAO R
	ON urm.ID_REGIAO_ATUACAO = R.ID_REGIAO_ATUACAO
INNER JOIN
	[TB_CARGO] [car]
 ON [urm].[ID_CARGO] = [car].[ID_CARGO]
INNER JOIN
	[TB_GRUPO_PAINEL] [gru]
 ON [car].[ID_GRUPO_PAINEL] = [gru].[ID_GRUPO_PAINEL]
INNER JOIN
	[TB_CABECALHO_PAINEL_META] [cpm]
 ON [gru].[ID_GRUPO_PAINEL] = [cpm].[ID_GRUPO_PAINEL]
INNER JOIN
	[TB_LINHA_PAINEL_META] [lpm]
 ON [cpm].[ID_META] = [lpm].[ID_META]
 INNER JOIN 
	[TB_ORIGEM_DADOS_PAINEL_META] [tod]
 ON [lpm].[ID_ORIGEM] = [tod].[ID_ORIGEM]
 LEFT JOIN
	[TB_GERENTE_SUPERVISOR] [gs]
 ON [urm].[ID_USUARIO_RM] = [gs].[ID_GERENTE_SUPERVISOR]
LEFT JOIN
	[TB_SUPERVISOR_CONSULTOR] [sc]
 ON [gs].[ID_SUPERVISOR] = [sc].[ID_SUPERVISOR_CONSULTOR]
 OR [urm].[ID_USUARIO_RM] = [sc].[ID_SUPERVISOR_CONSULTOR]
LEFT JOIN
	(SELECT
		 [ma].[ID_META_ANUAL]
		,[ma].[ID_USUARIO_RM]
		,[ma].[ID_LINHA_META]
		,[ma].[ID_UNIDADE_MEDIDA_PAINEL]
		,[ump].[DESCRICAO] AS UNIDADE_MEDIDA
		,[ma].[TOTAL] AS META_ANUAL
		,[ma].[VALOR_MINIMO]
		,[ma].[VALOR_MAXIMO]
		,[ma].[ID_STATUS]
		,[stp].[DESCRICAO] AS SITUACAO
		,[ma].[DATA_CRIACAO]
		,[ma].[DATA_ALTERACAO]
	 FROM
		 [TB_META_ANUAL] [ma]
	 INNER JOIN
		 [TB_UNIDADE_MEDIDA_PAINEL] [ump]
	  ON [ma].[ID_UNIDADE_MEDIDA_PAINEL] = [ump].[ID_UNIDADE_MEDIDA_PAINEL]
	 LEFT JOIN [TB_STATUS_PAINEL] [stp]
      ON [ma].[ID_STATUS] = [stp].[ID_STATUS]
	) AS [pma] ON [urm].[ID_USUARIO_RM] = [pma].[ID_USUARIO_RM]
			  AND [lpm].[ID_LINHA_META] = [pma].[ID_LINHA_META]
WHERE
	((@ID_USUARIO_RM = '00000000-0000-0000-0000-000000000000') OR ([urm].[ID_USUARIO_RM] = @ID_USUARIO_RM))
AND
	((@ID_CARGO = '00000000-0000-0000-0000-000000000000') OR ([urm].[ID_CARGO] = @ID_CARGO))
AND
	((@ID_GRUPO_PAINEL = '00000000-0000-0000-0000-000000000000') OR ([car].[ID_GRUPO_PAINEL] = @ID_GRUPO_PAINEL))
AND
	((@ID_META = '00000000-0000-0000-0000-000000000000') OR ([cpm].[ID_META] = @ID_META))
AND
	((@ID_LINHA_META = '00000000-0000-0000-0000-000000000000') OR ([lpm].[ID_LINHA_META] = @ID_LINHA_META))
AND
	((@ID_META_ANUAL = '00000000-0000-0000-0000-000000000000') OR ([pma].[ID_META_ANUAL] = @ID_META_ANUAL))
AND
	((@ID_STATUS = '00000000-0000-0000-0000-000000000000') OR ([pma].[ID_STATUS] = @ID_STATUS))
AND
	((@ID_PERIODO = '00000000-0000-0000-0000-000000000000') OR ([tod].[ID_PERIODO] = @ID_PERIODO))
AND
	[urm].[ATIVO] = 1
ORDER BY [urm].[NOME] ASC