	SELECT DISTINCT
		 ISNULL([SC].[ID_CONSULTOR], GS.ID_SUPERVISOR) AS ID_USUARIO_RM
		,(SELECT NOME FROM TB_USUARIO_RM WHERE ID_USUARIO_RM = ISNULL([SC].[ID_CONSULTOR], GS.ID_SUPERVISOR)) AS NOME
	FROM 
		[EBSA].[dbo].[TB_USUARIO_RM] [usu]
	LEFT JOIN
		TB_GERENTE_SUPERVISOR AS GS
		ON usu.ID_USUARIO_RM = GS.ID_GERENTE
	LEFT JOIN
		TB_SUPERVISOR_CONSULTOR AS SC
		ON (GS.ID_SUPERVISOR = SC.ID_SUPERVISOR OR usu.ID_USUARIO_RM = SC.ID_SUPERVISOR)
	WHERE 
		ISNULL([SC].[ID_CONSULTOR], GS.ID_SUPERVISOR) IN (
			SELECT ID_USUARIO_RM FROM TB_USUARIO_RM WHERE ((@ID_CARGO  = '00000000-0000-0000-0000-000000000000') OR (ID_CARGO = @ID_CARGO))
		) 
	AND
		((@ID_USUARIO_RM = '00000000-0000-0000-0000-000000000000') OR (USU.ID_USUARIO_RM =  @ID_USUARIO_RM))
	AND
		((@ID_REGIAO = '00000000-0000-0000-0000-000000000000') OR (USU.ID_REGIAO_ATUACAO = @ID_REGIAO))
	--AND
	--	[usu].[ID_USUARIO_RM] IN (
	--		SELECT [usu].[ID_USUARIO_RM]
	--		FROM [EBSA].[dbo].[TB_USUARIO_RM] [usu]
	--		INNER JOIN
	--			[TB_META_ANUAL] [ma] ON [usu].[ID_USUARIO_RM] = [ma].[ID_USUARIO_RM]
	--		GROUP BY [usu].[ID_USUARIO_RM]
	--	)
	--AND
	--	[usu].[ID_USUARIO_RM] IN (
	--		SELECT [usu].[ID_USUARIO_RM]
	--		FROM [EBSA].[dbo].[TB_USUARIO_RM] [usu]
	--		INNER JOIN
	--			[TB_META_FINANCEIRA] [mf] ON [usu].[ID_USUARIO_RM] = [mf].[ID_USUARIO_RM]
	--		GROUP BY [usu].[ID_USUARIO_RM]
	--	)
	AND [SC].[ID_CONSULTOR] IS NOT NULL
	AND
	[usu].[ATIVO] = 1









