	DECLARE @ID_STATUS_PENDENTE UNIQUEIDENTIFIER = (
		SELECT ID_STATUS FROM TB_STATUS_PAINEL WHERE DESCRICAO = 'Pendente'
	)

UPDATE 
	TB_CABECALHO_PAINEL_META
SET
	ID_STATUS = @ID_STATUS_PENDENTE
WHERE
	ID_GRUPO_PAINEL = @ID_GRUPO_PAINEL