DECLARE @ID_META UNIQUEIDENTIFIER = (
	SELECT ID_META FROM TB_CABECALHO_PAINEL_META WHERE ID_GRUPO_PAINEL = @ID_GRUPO_PAINEL
)

DELETE FROM TB_LINHA_PAINEL_META WHERE ID_META = @ID_META
DELETE FROM TB_CABECALHO_PAINEL_META WHERE ID_META = @ID_META