WITH RELATORIO
(
     [ID_RELATORIO]
    ,TITULO
    ,[PARTE_LIVRO]
    ,[QTD_TOTAL]
    ,[QTD_APROVADA]
    ,[QTD_FINALIZADA]
    ,[QTD_CAIU]
    ,[QTD_REPROVADA]
    ,[QTD_AGUARDANDO_APROVACAO]
    ,[QTD_EM_PESQUISA]
    ,[QTD_APROVACAO_ORCAMENTO]
    ,[DT_CADASTRO]
    ,[PORCENTAGEM_FINALIZADA]
    ,[QTD_OUTROS_STATUS]
    ,[IMPRESSO]
    ,[QTD_PENDENTE]
    ,[QTD_TOTAL_MENOS_CAIU]
    ,[ID_LIVRO]
)
AS
(
    SELECT
         R.[ID_RELATORIO]
        ,ISNULL(L.[TITULO], 'TÍTULO NÃO LOCALIZADO') AS TITULO
        ,R.[PARTE_LIVRO]
        ,R.[QTD_TOTAL]
        ,R.[QTD_APROVADA]
        ,R.[QTD_FINALIZADA]
        ,R.[QTD_CAIU]
        ,R.[QTD_REPROVADA]
        ,R.[QTD_AGUARDANDO_APROVACAO]
        ,R.[QTD_EM_PESQUISA]
        ,R.[QTD_APROVACAO_ORCAMENTO]
        ,R.[DT_CADASTRO]
        ,R.[PORCENTAGEM_FINALIZADA]
        ,R.[QTD_OUTROS_STATUS]
        ,R.[IMPRESSO]
        ,R.[QTD_PENDENTE]
        ,R.[QTD_TOTAL_MENOS_CAIU]
        ,L.[ID_LIVRO]
    FROM 
        TB_RELATORIO_ELVIS R WITH(NOLOCK)
    INNER JOIN
        TB_LIVRO_ELVIS L WITH(NOLOCK)
        ON R.ID_LIVRO = L.ID_LIVRO
    WHERE
        ((@IMPRESSO = '-1') OR (IMPRESSO = @IMPRESSO))
    AND
        ((@PROGRAMA = '-1') OR (PROGRAMA = @PROGRAMA))
    AND
        ((@DISCIPLINA = '-1') OR (DISCIPLINA = @DISCIPLINA))
    AND
        ((@COLECAO = '-1') OR (COLECAO = @COLECAO))
    AND
        ((@ANO = '-1') OR (ANO_ESCOLAR = @ANO))
)


SELECT 
	*,
	(SELECT COUNT(*) FROM RELATORIO) AS QTD_TOTAL_REGISTRO
FROM 
	RELATORIO
ORDER BY
    ID_LIVRO,
	TITULO,
	PARTE_LIVRO
	--CASE WHEN @ORDENACAO = 'preco_decrescente' THEN PRECO END DESC,
	--CASE WHEN @ORDENACAO = 'preco_crescente' THEN PRECO END ASC,
	--CASE WHEN @ORDENACAO = 'titulo_za' THEN TITULO END DESC,
	--CASE WHEN @ORDENACAO = 'titulo_az' THEN TITULO END ASC
OFFSET 
	(@NUMERO_PAGINA * @QUANTIDADE_MAX_REGISTROS) ROWS FETCH NEXT @QUANTIDADE_MAX_REGISTROS ROWS ONLY