WITH RELATORIO
(
     CODIGO_OBRA
    ,TITULO
    ,QTD_COLLECTION
    ,VALOR_GASTO
    ,VALOR_ORCADO
    ,PORCENTAGEM_GASTA
    ,DT_CADASTRO
    ,PROGRAMA
)
AS
(
SELECT 
     [CODIGO_OBRA]
    ,[TITULO]
    ,[QTD_COLLECTION]
    ,[VALOR_GASTO]
    ,[VALOR_ORCADO]
    ,[PORCENTAGEM_GASTA]
    ,[DT_CADASTRO]
    ,[PROGRAMA]
FROM 
    TB_OBRAS_ANDAMENTO
WHERE
    ((@DESCRICAO IS NULL) OR (TITULO = @DESCRICAO))
AND
    ((@PROGRAMA = '-1') OR (PROGRAMA = @PROGRAMA))
)

SELECT 
	*,
	(SELECT COUNT(*) FROM RELATORIO) AS QTD_TOTAL_REGISTRO
FROM 
	RELATORIO
ORDER BY
    TITULO
	--CASE WHEN @ORDENACAO = 'preco_decrescente' THEN PRECO END DESC,
	--CASE WHEN @ORDENACAO = 'preco_crescente' THEN PRECO END ASC,
	--CASE WHEN @ORDENACAO = 'titulo_za' THEN TITULO END DESC,
	--CASE WHEN @ORDENACAO = 'titulo_az' THEN TITULO END ASC
OFFSET 
	(@NUMERO_PAGINA * @QUANTIDADE_MAX_REGISTROS) ROWS FETCH NEXT @QUANTIDADE_MAX_REGISTROS ROWS ONLY