DECLARE @ID_GRUPO INT = (SELECT ID_GRUPO FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO)


IF(EXISTS(SELECT 1 FROM TB_ORCAMENTO_OBRA WHERE ID_PRODUTO = @ID_PRODUTO))
BEGIN
	UPDATE TB_ORCAMENTO_OBRA SET VALOR = @VALOR, ID_USUARIO_ALTERACAO = @ID_USUARIO, DT_ALTERACAO = GETDATE() WHERE ID_PRODUTO = @ID_PRODUTO
END
ELSE
BEGIN
	INSERT INTO TB_ORCAMENTO_OBRA(ID_PRODUTO, VALOR, ID_USUARIO_CADASTRO, ID_GRUPO)
	VALUES(@ID_PRODUTO, @VALOR, @ID_USUARIO, @ID_GRUPO)
END
