UPDATE [dbo].[TB_NOME_CAPA]
   SET [ID_SEGMENTO] = @ID_SEGMENTO
      ,[ID_DISCIPLINA] = @ID_DISCIPLINA
      ,[ID_USUARIO] = @ID_USUARIO
      ,[DATA_INCLUSAO] = @DATA_INCLUSAO
      ,[ATIVO] = @ATIVO
 WHERE [ID_NOME_CAPA] = @ID_NOME_CAPA