--IF(EXISTS(SELECT 1 FROM TB_META_ANUAL WHERE ID_USUARIO_RM = @ID_USUARIO_RM))
--BEGIN
--	UPDATE TB_META_ANUAL SET
--		 ID_UNIDADE_MEDIDA_PAINEL = @ID_UNIDADE_MEDIDA_PAINEL
--		,TOTAL = @TOTAL
--		,VALOR_MINIMO = @VALOR_MINIMO
--		,VALOR_MAXIMO = @VALOR_MAXIMO
--		,DATA_ALTERACAO = GETDATE()
--		,ID_STATUS = @ID_STATUS
--	WHERE
--		ID_USUARIO_RM = @ID_USUARIO_RM
--END
--ELSE
--BEGIN
	INSERT INTO TB_META_ANUAL 
		(ID_META_ANUAL
		,ID_USUARIO_RM
		,ID_LINHA_META
		,ID_UNIDADE_MEDIDA_PAINEL
		,TOTAL
		,VALOR_MINIMO
		,VALOR_MAXIMO
		,DATA_CRIACAO
		,ID_STATUS)
	VALUES
		(NEWID()
		,@ID_USUARIO_RM
		,@ID_LINHA_META
		,@ID_UNIDADE_MEDIDA_PAINEL
		,@TOTAL
		,@VALOR_MINIMO
		,@VALOR_MAXIMO
		,GETDATE()
		,(SELECT ID_STATUS FROM TB_STATUS_PAINEL WHERE DESCRICAO = 'Rascunho'))	
--END