SELECT
	 [pma].[ID_META_FINANCEIRA]
	,[urm].[ID_USUARIO_RM]
	,[urm].[NOME]
	,[car].[DESCRICAO] AS CARGO
	,[pma].[ID_STATUS]
	,[pma].[SITUACAO]
	,[pma].[META_RECEITA_LIQUIDA]
	,[pma].[VALOR_RECEBIMENTO]
	,[pma].[DATA_CRIACAO]
	,[pma].[DATA_ALTERACAO]
	,[pma].[META_RECEITA_LIQUIDA_CALC]

FROM
	[TB_USUARIO_RM] [urm]
INNER JOIN
	[TB_CARGO] [car]
	 ON [urm].[ID_CARGO] = [car].[ID_CARGO]
LEFT JOIN
	(SELECT
		 [mF].[ID_META_FINANCEIRA]
		,[mF].[ID_USUARIO_RM]
		,[mF].[ID_STATUS]
		,[mF].[META_RECEITA_LIQUIDA]
		,[mF].[VALOR_RECEBIMENTO]
		,[stp].[DESCRICAO] AS SITUACAO
		,[mF].[DATA_CRIACAO]
		,[mF].[DATA_ALTERACAO]
		,[mF].[ID_PERIODO]
		,[mF].[META_RECEITA_LIQUIDA_CALC]
	 FROM
		 [TB_META_FINANCEIRA] [mF]
	 LEFT JOIN 
		[TB_STATUS_PAINEL] [stp]
		ON [mF].[ID_STATUS] = [stp].[ID_STATUS]
	) AS [pma] ON [urm].[ID_USUARIO_RM] = [pma].[ID_USUARIO_RM]
WHERE
	((@ID_PERIODO IS NULL OR @ID_PERIODO = '00000000-0000-0000-0000-000000000000') OR ([pma].[ID_PERIODO] = @ID_PERIODO))
AND
	[urm].[ATIVO] = 1
ORDER BY 
	[urm].[NOME] ASC