
SELECT NC.[ID_NOME_CAPA]
      ,NC.[ID_AUTOR_BENEFICIARIO]
      ,NC.[NOME_CAPA]
      ,NC.[ID_SEGMENTO]
      ,S.SEGM_DESCRICAO
	  ,NC.[ID_DISCIPLINA]
	  ,D.DISC_NOME
      ,NC.[ID_USUARIO]
	  ,U.NOME
      ,NC.[DATA_INCLUSAO]
      ,NC.[ATIVO]
  FROM [dbo].[TB_NOME_CAPA] NC
LEFT JOIN [dbo].[SEGMENTO] S ON NC.ID_SEGMENTO = S.SEGM_ID
LEFT JOIN [dbo].[DISCIPLINA] D ON NC.ID_DISCIPLINA = D.DISC_ID
LEFT JOIN [dbo].[USUARIO] U ON NC.ID_USUARIO = U.ID_USUARIO
WHERE [ID_NOME_CAPA] = @ID_NOME_CAPA
AND NC.[ATIVO] = 1