SELECT [ID_CORRESPONDENCIA]
      ,[ID_AUTOR_BENEFICIARIO]
      ,[AGENDA]
      ,[ASSUNTO]
      ,[OBS]
      ,[CODIGO_INTERNO]
      ,[ATIVO]
  FROM [dbo].[TB_CORRESPONDENCIA_AUTOR_BENEFICIARIO] 
  WHERE [ID_CORRESPONDENCIA] = @ID_CORRESPONDENCIA