SELECT  
     O.ID_ORIGEM
    ,CONCAT(P.DESCRICAO,' | ' ,O.DESCRICAO) AS DESCRICAO
FROM 
    TB_ORIGEM_DADOS_PAINEL_META AS O
INNER JOIN
	TB_PERIODO_META AS P
	ON O.ID_PERIODO = P.ID_PERIODO
WHERE
    SCRIPT IS NOT NULL
AND
   DATEDIFF(MONTH, DATEADD(MONTH, 10, P.DATA_INICIO), GETDATE()) <= 0