SELECT 
    U.ID_USUARIO,
    U.NOME,
    U.EMAIL,
    U.COD_USUARIO,
    U.CONTA_AD,
    G.ID_GRUPO,
    G.ID_GRUPO_AD,
    G.DESCRICAO GRUPODESC,
    G.DEPARTAMENTO,
    CT.CTT_CUSTO 
FROM 
    USUARIO U
INNER JOIN
    USUARIO_GRUPO AS UG
    ON U.ID_USUARIO = UG.ID_USUARIO
INNER JOIN 
    GRUPO G ON G.ID_GRUPO = UG.ID_GRUPO
INNER JOIN 
    __protheusAmbiente__.dbo.CTT010 as CT 
    on CT.CTT_DESC01 COLLATE Latin1_General_CI_AS = G.DEPARTAMENTO COLLATE Latin1_General_CI_AS
WHERE 
    __queryEmail__ 
AND 
    U.ATIVO = 1