SELECT
	 [mf].[ID_META_FINANCEIRA]
	,[mf].[ID_USUARIO_RM]
	,[urm].[NOME]
	,[car].[DESCRICAO] AS CARGO
	,[stp].[DESCRICAO] AS SITUACAO
	,[mf].[ID_STATUS]
	,[mf].[META_RECEITA_LIQUIDA]
	,[mf].[VALOR_RECEBIMENTO]
	,[mf].[DATA_CRIACAO]
	,[mf].[DATA_ALTERACAO]
	,[mf].[META_RECEITA_LIQUIDA_CALC]
FROM
	 [TB_META_FINANCEIRA] [mf]
INNER JOIN
	 [TB_USUARIO_RM] [urm]
  ON [mf].[ID_USUARIO_RM] = [urm].[ID_USUARIO_RM]
INNER JOIN
	 [TB_CARGO] [car]
  ON [urm].[ID_CARGO] = [car].[ID_CARGO]
INNER JOIN
	 [TB_STATUS_PAINEL] [stp]
  ON [mf].[ID_STATUS] = [stp].[ID_STATUS]
WHERE
	((@ID_USUARIO_RM = '00000000-0000-0000-0000-000000000000') OR ([mf].[ID_USUARIO_RM] = @ID_USUARIO_RM))
  AND
	((@ID_META_FINANCEIRA = '00000000-0000-0000-0000-000000000000') OR ([mf].[ID_META_FINANCEIRA] = @ID_META_FINANCEIRA))
AND
	[urm].[ATIVO] = 1