IF(NOT EXISTS(SELECT 1 FROM LIVRO WHERE CODIGO = @CODIGO))
BEGIN
    INSERT INTO [dbo].[LIVRO]
           ([CODIGO]
           ,[OBRA]
           ,[DATA]
           ,[SERIE]
           ,[ENCADERNACAO]
           ,[FORMATO]
           ,[CORES]
           ,[PAGINAS]
           ,[TIPO]
           ,[STATUS]
           ,[DSTATUS]
           ,[GRAVAR]
           ,[INICIO]
           ,[PREVISAO]
           ,[TERMINO]
           ,[OBS]
           ,[PROJETO]
           ,[VOLUME]
           ,[OPERADOR]
           ,[DESCRICAO]
           ,[COLECAO]
           ,[CONDICAO]
           ,[SITUACAO]
           ,[COD_IMAGEM]
           ,[MATERIA]
           ,[AREA]
           ,[PAG_MP]
           ,[DT_INC]
           ,[OPERADOR_ALT]
           ,[DT_ALT]
           ,[DATAD]
           ,[DATAE]
           ,[INFGERAL]
           ,[DVD]
           ,[OBRA_ANTIGA]
           ,[PSEUDONIMO]
           ,[NM_EDITORA]
           ,[TITULO]
           ,[TITULO_ORIGINAL]
           ,[ANO_PUB]
           ,[COLABORADOR]
           ,[TEXT_COLAB]
           ,[EDICAO]
           ,[REIMP]
           ,[CO_EDICAO]
           ,[TIT_SC]
           ,[NUM_PUB]
           ,[P_PRECEDE]
           ,[INC_BIB]
           ,[INC_APEN]
           ,[TIT_ANT]
           ,[TIT_CON]
           ,[TIT_SUP]
           ,[TIT_OUT]
           ,[SUPLEM]
           ,[ISBN]
           ,[P_CHAVE]
           ,[CENTRO_CUSTO]
           ,[USER_TROCA_CODIGO]
           ,[DATA_TROCA_CODIGO]
           ,[PRE_TRIAGEM]
           ,[TRIAGEM]
           ,[PROVAS]
           ,[NOVA_REFORMULADA]
           ,[REFORMULADA]
           ,[ANO_PROD]
           ,[INICIO2]
           ,[PREVISAO2]
           ,[TERMINO2])
     VALUES
           (@CODIGO
           ,@OBRA
           ,@DATA
           ,@SERIE
           ,@ENCADERNACAO
           ,@FORMATO
           ,@CORES
           ,@PAGINAS
           ,@TIPO
           ,@STATUS
           ,@DSTATUS
           ,@GRAVAR
           ,@INICIO
           ,@PREVISAO
           ,@TERMINO
           ,@OBS
           ,@PROJETO
           ,@VOLUME
           ,@OPERADOR
           ,@DESCRICAO
           ,@COLECAO
           ,@CONDICAO
           ,@SITUACAO
           ,@COD_IMAGEM
           ,@MATERIA
           ,@AREA
           ,@PAG_MP
           ,@DT_INC
           ,@OPERADOR_ALT
           ,@DT_ALT
           ,@DATAD
           ,@DATAE
           ,@INFGERAL
           ,@DVD
           ,@OBRA_ANTIGA
           ,@PSEUDONIMO
           ,@NM_EDITORA
           ,@TITULO
           ,@TITULO_ORIGINAL
           ,@ANO_PUB
           ,@COLABORADOR
           ,@TEXT_COLAB
           ,@EDICAO
           ,@REIMP
           ,@CO_EDICAO
           ,@TIT_SC
           ,@NUM_PUB
           ,@P_PRECEDE
           ,@INC_BIB
           ,@INC_APEN
           ,@TIT_ANT
           ,@TIT_CON
           ,@TIT_SUP
           ,@TIT_OUT
           ,@SUPLEM
           ,@ISBN
           ,@P_CHAVE
           ,@CENTRO_CUSTO
           ,@USER_TROCA_CODIGO
           ,@DATA_TROCA_CODIGO
           ,@PRE_TRIAGEM
           ,@TRIAGEM
           ,@PROVAS
           ,@NOVA_REFORMULADA
           ,@REFORMULADA
           ,@ANO_PROD
           ,@INICIO2
           ,@PREVISAO2
           ,@TERMINO2)
END