IF(EXISTS(SELECT 1 FROM TB_PERMISSAO_REQUISICAO WHERE ID_USUARIO = @ID_USUARIO))
BEGIN
	UPDATE TB_PERMISSAO_REQUISICAO 
		SET 
		 APROVA_REQUISICAO_SUPERVISOR = @APROVA_REQUISICAO_SUPERVISOR
		,REPROVA_REQUISICAO_SUPERVISOR = @REPROVA_REQUISICAO_SUPERVISOR
		,CANCELA_REQUISICAO_SUPERVISOR = @CANCELA_REQUISICAO_SUPERVISOR
		,APROVA_REQUISICAO_GERENTE = @APROVA_REQUISICAO_GERENTE
		,REPROVA_REQUISICAO_GERENTE = @REPROVA_REQUISICAO_GERENTE
		,CANCELA_REQUISICAO_GERENTE = @CANCELA_REQUISICAO_GERENTE
	WHERE ID_USUARIO = @ID_USUARIO
END
ELSE
BEGIN
	INSERT INTO TB_PERMISSAO_REQUISICAO(
		 ID_USUARIO
		,APROVA_REQUISICAO_SUPERVISOR 
		,REPROVA_REQUISICAO_SUPERVISOR
		,CANCELA_REQUISICAO_SUPERVISOR
		,APROVA_REQUISICAO_GERENTE
		,REPROVA_REQUISICAO_GERENTE
		,CANCELA_REQUISICAO_GERENTE) 
	VALUES(
		 @ID_USUARIO
		,@APROVA_REQUISICAO_SUPERVISOR 
		,@REPROVA_REQUISICAO_SUPERVISOR
		,@CANCELA_REQUISICAO_SUPERVISOR
		,@APROVA_REQUISICAO_GERENTE
		,@REPROVA_REQUISICAO_GERENTE
		,@CANCELA_REQUISICAO_GERENTE) 
END