IF(NOT EXISTS(SELECT 1 FROM ENVIO_OBRA WHERE OBRA = @OBRA))
BEGIN
    INSERT INTO [dbo].[ENVIO_OBRA]
               ([OBRA]
               ,[STATUS]
               ,[TIPO]
               ,[EMISSAO]
               ,[DIG]
               ,[NOME_ARQUIVO]
               ,[FORNECEDOR]
               ,[LOJA]
               ,[CODIGO]
               ,[DIGA]
               ,[SITUACAO]
               ,[OPERADOR]
               ,[TAMANHO]
               ,[VALOR]
               ,[AUTORIZACAO]
               ,[TEXTO]
               --,[IMAGEM]
               ,[TEXTO_A]
               ,[USUARIO]
               ,[MOVIMENTADO]
               ,[ORIGEM]
               ,[LEG_FIM]
               ,[REFERENCIA]
               ,[VENCIMENTO]
               ,[REQUER_AUTOR]
               ,[OBRA_ANTIGA]
               ,[LEGENDA_OLD]
               ,[DESCRICAO]
               ,[DATA_ALTERACAO_DIGA]
               ,[OBS]
               ,[LEGENDA_AUTOR_OLD]
               ,[LICENC]
               ,[CREDITO]
               ,[REQ_GERADA]
               ,[REQ_DATA]
               ,[REQ_INCLUIDOR]
               ,[REQUISICAO]
               ,[DATA_FINALIZADA]
               ,[QUEM_FINALIZOU]
               ,[NF]
               ,[COD_INTERNO]
               ,[USERALT]
               ,[DISCIPLINA]
               ,[ANO]
               ,[ENTRA_GALERIA_IMAGEM]
               ,[PORTAL]
               ,[UNIDADE]
               ,[PAGINA]
               ,[LEGENDA]
               ,[OBS_ICONOGRAFIA]
               ,[CONTRATO_GERADO]
               ,[CONTRATO_USUARIO]
               ,[CONTRATO_INCLUIDO]
               ,[CONTRATO]
               ,[LEGENDA_AUTOR_OLD2]
               ,[LEGENDA_AUTOR]
               ,[INFO_DIAGRAMACAO]
               ,[ID_ELVIS])
         VALUES
               (@OBRA
               ,@STATUS
               ,@TIPO
               ,@EMISSAO
               ,@DIG
               ,@NOME_ARQUIVO
               ,@FORNECEDOR
               ,@LOJA
               ,@CODIGO
               ,@DIGA
               ,@SITUACAO
               ,@OPERADOR
               ,@TAMANHO
               ,@VALOR
               ,@AUTORIZACAO
               ,@TEXTO
               --,@IMAGEM
               ,@TEXTO_A
               ,@USUARIO
               ,@MOVIMENTADO
               ,@ORIGEM
               ,@LEG_FIM
               ,@REFERENCIA
               ,@VENCIMENTO
               ,@REQUER_AUTOR
               ,@OBRA_ANTIGA
               ,@LEGENDA_OLD
               ,@DESCRICAO
               ,@DATA_ALTERACAO_DIGA
               ,@OBS
               ,@LEGENDA_AUTOR_OLD
               ,@LICENC
               ,@CREDITO
               ,@REQ_GERADA
               ,@REQ_DATA
               ,@REQ_INCLUIDOR
               ,@REQUISICAO
               ,@DATA_FINALIZADA
               ,@QUEM_FINALIZOU
               ,@NF
               ,@COD_INTERNO
               ,@USERALT
               ,@DISCIPLINA
               ,@ANO
               ,@ENTRA_GALERIA_IMAGEM
               ,@PORTAL
               ,@UNIDADE
               ,@PAGINA
               ,@LEGENDA
               ,@OBS_ICONOGRAFIA
               ,@CONTRATO_GERADO
               ,@CONTRATO_USUARIO
               ,@CONTRATO_INCLUIDO
               ,@CONTRATO
               ,@LEGENDA_AUTOR_OLD2
               ,@LEGENDA_AUTOR
               ,@INFO_DIAGRAMACAO
               ,@ID_ELVIS)
END