UPDATE [dbo].[PRODUTO]
   SET [PROD_VIDEO] = @PROD_VIDEO
   ,   [PROD_PRECO] = @PROD_PRECO
 WHERE [PROD_ID] = @ID_PRODUTO

 UPDATE [dbo].[PRODUTO]
	SET [PROD_INTEGRADO] = 'naoIntegrado'
WHERE [PROD_ID] = @ID_PRODUTO