DECLARE @ABREVIACAO_VERSAO VARCHAR(MAX) = (
	SELECT ABREVIACAO FROM TB_VERSAO WHERE CODIGO = @VERSAO
)

IF(NOT EXISTS(SELECT 1 FROM PRODUTO WHERE PROD_EBSA = @CODIGO_EBSA))
BEGIN
	INSERT PRODUTO(PROD_MERCADO,PROD_AEDU ,PROD_DISC ,PROD_MIDI ,PROD_TIPO ,PROD_EDICAO ,PROD_VERSAO, PROD_EBSA, PROD_TITULO, PRODUTO_PROVISORIO)
	VALUES(@MERCADO, @ANO, @DISCIPLINA, @MIDIA, @TIPO, @EDICAO, @ABREVIACAO_VERSAO, @CODIGO_EBSA, @TITULO, 1)
END
