INSERT INTO [dbo].[TB_CADERNO_PRODUTO]
           ([ID_PRODUTO]
           ,[CADERNO_PAGINAS]
           ,[CADERNO_ALT]
           ,[CADERNO_LARG]
           ,[CADERNO_TIPO]
           ,[CADERNO_TIPO_OUTROS]
           ,[CADERNO_PESO]
           ,[CADERNO_MIOLO_CORES]
           ,[CADERNO_MIOLO_TP_PAPEL]
           ,[CADERNO_MIOLO_GRAMATURA]
           ,[CADERNO_MIOLO_OBS]
           ,[CADERNO_CAPA_CORES]
           ,[CADERNO_CAPA_TP_PAPEL]
           ,[CADERNO_CAPA_GRAMATURA]
           ,[CADERNO_CAPA_ORELHA]
           ,[CADERNO_CAPA_ACABAMENTO]
           ,[CADERNO_CAPA_OBS]
           ,[CADERNO_CAPA_ACAB_LOMBADA])
     VALUES
           (@ID_PRODUTO
           ,@CADERNO_PAGINAS
           ,@CADERNO_ALT
           ,@CADERNO_LARG
           ,@CADERNO_TIPO
           ,@CADERNO_TIPO_OUTROS
           ,@CADERNO_PESO
           ,@CADERNO_MIOLO_CORES
           ,@CADERNO_MIOLO_TP_PAPEL
           ,@CADERNO_MIOLO_GRAMATURA
           ,@CADERNO_MIOLO_OBS
           ,@CADERNO_CAPA_CORES
           ,@CADERNO_CAPA_TP_PAPEL
           ,@CADERNO_CAPA_GRAMATURA
           ,@CADERNO_CAPA_ORELHA
           ,@CADERNO_CAPA_ACABAMENTO
           ,@CADERNO_CAPA_OBS
           ,@CADERNO_CAPA_ACAB_LOMBAD)