INSERT INTO [dbo].[TB_AUTOR_BENEFICIARIO]
           ([NOME]
           ,[CODIGO]
           ,[LOJA]
           ,[CPF_CNPJ]
           ,[SITUACAO]
           ,[TIPO_EMPRESA]
           ,[INSCRICAO]
           ,[TELEFONE_RES]
           ,[TELEFONE_CEL]
           ,[TELEFONE_COM]
           ,[CONTATO]
           ,[CEP]
           ,[ID_ESTADO]
           ,[CIDADE]
           ,[BAIRRO]
           ,[LOGRADOURO]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[CORRENTISTA]
           ,[CORRENTISTA_CPF_CNPJ]
           ,[BANCO]
           ,[AGENCIA]
           ,[ID_TIPO_CONTA]
           ,[NUMERO_CONTA]
           ,[DATA_AUTORIZACAO]
           ,[ENVIAR_DEMONSTRATIVO]
           ,[PAGAMENTO_MINIMO]
           ,[EMITE_RECIBO]
           ,[EMAIL_CONTADOR]
           ,[OBSERVACAO]
           ,[ID_USUARIO_INCLUSAO]
           ,[DATA_INCLUSAO]
           ,[ID_TIPO_CADASTRO]
           ,[ATIVO]
           ,[INCLUIDO_POR]
           ,[TIPO_PESSOA])
     VALUES
           (@NOME
           ,@CODIGO
           ,@LOJA
           ,@CPF_CNPJ
           ,@SITUACAO
           ,@TIPO_EMPRESA
           ,@INSCRICAO
           ,@TELEFONE_RES
           ,@TELEFONE_CEL
           ,@TELEFONE_COM
           ,@CONTATO
           ,@CEP
           ,@ID_ESTADO
           ,@CIDADE
           ,@BAIRRO
           ,@LOGRADOURO
           ,@NUMERO
           ,@COMPLEMENTO
           ,@CORRENTISTA
           ,@CORRENTISTA_CPF_CNPJ
           ,@BANCO
           ,@AGENCIA
           ,@ID_TIPO_CONTA
           ,@NUMERO_CONTA
           ,@DATA_AUTORIZACAO
           ,@ENVIAR_DEMONSTRATIVO
           ,@PAGAMENTO_MINIMO
           ,@EMITE_RECIBO
           ,@EMAIL_CONTADOR
           ,@OBSERVACAO
           ,@ID_USUARIO_INCLUSAO
           ,@DATA_INCLUSAO
           ,@ID_TIPO_CADASTRO
           ,@ATIVO
           ,@INCLUIDO_POR
           ,@TIPO_PESSOA)

SELECT @@IDENTITY;