DECLARE @ID_STATUS_PUBLICADO UNIQUEIDENTIFIER = '0616D711-28CD-4714-98A9-3F9B85FEF76A'

SELECT DISTINCT
	L.ID_ORIGEM,
	L.ID_LINHA_META,
	U.ID_USUARIO_RM
FROM
	TB_CABECALHO_PAINEL_META AS C
INNER JOIN
	TB_LINHA_PAINEL_META AS L
	ON C.ID_META = L.ID_META
INNER JOIN
	TB_CARGO AS CG
	ON C.ID_GRUPO_PAINEL = CG.ID_GRUPO_PAINEL
INNER JOIN
	TB_USUARIO_RM AS U
	ON CG.ID_CARGO = U.ID_CARGO
INNER JOIN
	TB_META_ANUAL AS MA
	ON MA.ID_USUARIO_RM = U.ID_USUARIO_RM
WHERE
	MA.ID_STATUS = @ID_STATUS_PUBLICADO
AND
	U.ATIVO = 1
	