DECLARE @ID_GERENTE UNIQUEIDENTIFIER = '635881D0-FD3D-4020-8229-5F6207B5ABF2'
DECLARE @ID_SUPERVISOR UNIQUEIDENTIFIER = '12AFAEFA-F154-4B13-92E7-E19C052B6710'

DECLARE @ID_CARGO UNIQUEIDENTIFIER = (
	SELECT ID_CARGO FROM TB_USUARIO_RM WHERE ID_USUARIO_RM = @ID_USUARIO
)

DECLARE @CODIGO_PROTHEUS VARCHAR(MAX) = (
	SELECT CODIGO_PROTHEUS FROM TB_USUARIO_RM WHERE ID_USUARIO_RM = @ID_USUARIO
)

IF(@ID_CARGO = @ID_GERENTE)
BEGIN
	INSERT INTO TB_GERENTE_SUPERVISOR(ID_GERENTE, ID_SUPERVISOR)
	SELECT 
		@ID_USUARIO,
		(SELECT ID_USUARIO_RM FROM TB_USUARIO_RM WHERE CODIGO_PROTHEUS = S.A3_COD COLLATE Latin1_General_CI_AS)  
	FROM 
		TB_USUARIO_RM U 
	INNER JOIN 
		__BANCO__.dbo.SA3010 S
		ON U.CODIGO_PROTHEUS = S.A3_COD COLLATE Latin1_General_CI_AS
	WHERE
		S.A3_SUPER = @CODIGO_PROTHEUS
	AND
		U.ATIVO = 1

END
ELSE IF(@ID_CARGO = @ID_SUPERVISOR)
BEGIN
	INSERT INTO TB_SUPERVISOR_CONSULTOR(ID_SUPERVISOR, ID_CONSULTOR)
	SELECT 
		@ID_USUARIO,
		(SELECT ID_USUARIO_RM FROM TB_USUARIO_RM WHERE CODIGO_PROTHEUS = S.A3_COD COLLATE Latin1_General_CI_AS)  
	FROM 
		TB_USUARIO_RM U 
	INNER JOIN 
		__BANCO__.dbo.SA3010 S
		ON U.CODIGO_PROTHEUS = S.A3_COD COLLATE Latin1_General_CI_AS
	WHERE
		S.A3_SUPER = @CODIGO_PROTHEUS
	AND
		U.ATIVO = 1
END