IF(NOT EXISTS(SELECT 1 FROM TB_REGIAO_ATUACAO WHERE CODIGO_PROTHEUS = @CHAVE))
	INSERT INTO TB_REGIAO_ATUACAO(DESCRICAO, CODIGO_PROTHEUS) VALUES(@DESCRICAO, @CHAVE)
ELSE
	UPDATE TB_REGIAO_ATUACAO SET DESCRICAO = @DESCRICAO WHERE CODIGO_PROTHEUS = @CHAVE