DECLARE @ID_REGIAO UNIQUEIDENTIFIER = (
	SELECT ID_REGIAO_ATUACAO FROM TB_REGIAO_ATUACAO WHERE CODIGO_PROTHEUS = (
		SELECT A3_REGIAO COLLATE Latin1_General_CI_AS FROM __BANCO__.dbo.SA3010 WHERE A3_COD = (SELECT CODIGO_PROTHEUS COLLATE Latin1_General_CI_AS FROM EBSA.dbo.TB_USUARIO_RM WHERE ID_USUARIO_RM = @ID_USUARIO) AND D_E_L_E_T_ =' '
	)
)

UPDATE TB_USUARIO_RM SET ID_REGIAO_ATUACAO = @ID_REGIAO WHERE ID_USUARIO_RM = @ID_USUARIO