IF(EXISTS(SELECT 1 FROM TB_META_REAL WHERE ID_USUARIO_RM = @ID_USUARIO_RM AND ID_LINHA_META = @ID_LINHA_META))
BEGIN
	UPDATE 
		TB_META_REAL 
	SET
		REALIZADO = @VALOR
	WHERE
		ID_USUARIO_RM = @ID_USUARIO_RM
	AND
		ID_LINHA_META = @ID_LINHA_META
END
ELSE
BEGIN
	INSERT INTO TB_META_REAL(ID_META_REAL, ID_USUARIO_RM, ID_LINHA_META, REALIZADO, PONDERADO)
	VALUES(NEWID(), @ID_USUARIO_RM, @ID_LINHA_META, @VALOR, 0)
END
