DECLARE @ID_CARGO UNIQUEIDENTIFIER = (
	SELECT ID_CARGO FROM TB_CARGO WHERE DESCRICAO = @DESCRICAO_CARGO
)

DECLARE @ID_FILIAL UNIQUEIDENTIFIER = (
	SELECT ID_FILIAL FROM TB_FILIAL WHERE CODIGO_FILIAL = @CODIGO_FILIAL
)

DECLARE @CODIGO_PROTHEUS VARCHAR(MAX) = (
	SELECT A3_COD FROM __BANCO__.dbo.SA3010 WHERE A3_CGC = @CPF AND D_E_L_E_T_ = ' ' 
)

DECLARE @ATIVO BIT;

	IF(@DATA_FIM = CAST('00010101' AS DATETIME2))
	BEGIN
		SET @ATIVO = 1
		SET @DATA_FIM = NULL
	END
	ELSE
		SET @ATIVO = 0




IF(NOT EXISTS(SELECT 1 FROM TB_USUARIO_RM WHERE CPF = @CPF))
BEGIN
	DECLARE @ID_SECAO UNIQUEIDENTIFIER = (
		SELECT ID_SECAO FROM TB_SECAO WHERE CODIGO_SECAO = @CODIGO_SECAO
	)
	INSERT INTO TB_USUARIO_RM(
		ID_CARGO,
		NUMERO_CHAPA,
		ID_SECAO,
		NOME,
		ID_FILIAL,
		DATA_INICIO,
		DATA_FIM,
		CPF,
		ATIVO,
		CODIGO_PROTHEUS
	)
	SELECT
		@ID_CARGO, 
		@NUMERO_CHAPA,
		@ID_SECAO,
		@NOME,
		@ID_FILIAL,
		@DATA_INICIO,
		@DATA_FIM,
		@CPF,
		@ATIVO,
		@CODIGO_PROTHEUS

END
ELSE
BEGIN
	UPDATE TB_USUARIO_RM 
	SET
		ID_CARGO = @ID_CARGO,
		ID_FILIAL = @ID_FILIAL,
		NOME = @NOME,
		DATA_FIM = @DATA_FIM,
		ATIVO = @ATIVO,
		CODIGO_PROTHEUS = @CODIGO_PROTHEUS
	WHERE
		CPF = @CPF
	
END